// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyCQLFufXAgW3i6eM_5pp6lnJOJe803topA',
    // appId: '1:456696145433:android:5508b3b1d7d033172fac88',
    // messagingSenderId: '456696145433',
    // projectId: 'gyminder-70ebb',
    // storageBucket: 'gyminder-70ebb.appspot.com',
    apiKey: dotenv.env['API_KEY_Android']!,
    appId: dotenv.env['APP_ID_Android']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_Android']!,
    projectId: dotenv.env['PROJECT_ID_Android']!,
    storageBucket: dotenv.env['STORAGE_BUCKET_Android']!,
  );
}
